name: Stock Check

on:
  schedule:
    - cron: '30 0 * * 1-5'
    - cron: '00 2 * * 1-5'
    - cron: '00 5 * * 1-5'
    - cron: '30 6 * * 1-5'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3에서 v4로 최신화
      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 최신화
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install yfinance pandas requests
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python stock-alert.py
